package rpcnode.toolkit.chains.sui.infrastructure

import rpcnode.toolkit.nodes.infrastructure.host.HostSystemdUnitTemplate

/**
 * Renders sui-node systemd unit + fullnode.yaml pins (full-history + archival fallback).
 * Capacity literals must stay identical to `chains/sui/network.yml` clientConfig.bindings.
 */
object SuiUnitBodies
{
    const val NODE_NOFILE = 1_048_576
    const val NUM_EPOCHS_TO_RETAIN = "18446744073709551615"
    const val ARCHIVE_CONCURRENCY = 5
    const val ENABLE_EVENT_PROCESSING = true

    const val FULLNODE_YAML = "fullnode.yaml"
    const val GENESIS_BLOB = "genesis.blob"
    const val RELATIVE_LOG = "logs/sui.log"

    fun unit(
        env: String,
        nodeDir: String,
        execStart: String,
        logFile: String,
        nofile: Int = NODE_NOFILE,
    ): String
    {
        return HostSystemdUnitTemplate.render(
            HostSystemdUnitTemplate.load("sui", "node.service.tmpl"),
            mapOf(
                "description" to "Sui fullnode ($env) — RpcNode",
                "node_dir" to nodeDir,
                "exec_start" to execStart,
                "log_file" to logFile,
                "nofile" to nofile.coerceAtLeast(1024).toString(),
            ),
        )
    }

    fun fullnodeYaml(
        env: String,
        dbPath: String,
        metricsPort: Int,
        rpcPort: Int,
        p2pPort: Int,
        genesisPath: String,
        archiveUrl: String,
        enableEventProcessing: Boolean = ENABLE_EVENT_PROCESSING,
        numEpochsToRetain: String = NUM_EPOCHS_TO_RETAIN,
        archiveConcurrency: Int = ARCHIVE_CONCURRENCY,
    ): String
    {
        val envId = SuiClusters.normalizeEnv(env)
        return buildString {
            appendLine("# Generated by toolkit — sui/$envId")
            appendLine("# Docs: https://docs.sui.io/operators/full-node/sui-full-node")
            appendLine("db-path: ${yamlQuote(dbPath)}")
            appendLine()
            appendLine("network-address: \"/ip4/127.0.0.1/tcp/8080/http\"")
            appendLine("metrics-address: \"127.0.0.1:$metricsPort\"")
            appendLine("json-rpc-address: \"127.0.0.1:$rpcPort\"")
            appendLine("enable-event-processing: $enableEventProcessing")
            appendLine()
            appendLine("p2p-config:")
            appendLine("  listen-address: \"0.0.0.0:$p2pPort\"")
            appendLine()
            appendLine("genesis:")
            appendLine("  genesis-file-location: ${yamlQuote(genesisPath)}")
            appendLine()
            appendLine("# Retain as many epochs as practical locally; archival fallback for older history.")
            appendLine("authority-store-pruning-config:")
            appendLine("  num-latest-epoch-dbs-to-retain: 3")
            appendLine("  epoch-db-pruning-period-secs: 3600")
            appendLine("  num-epochs-to-retain: $numEpochsToRetain")
            appendLine("  max-checkpoints-in-batch: 10")
            appendLine("  max-transactions-in-batch: 1000")
            appendLine("  pruning-run-delay-seconds: 60")
            appendLine()
            appendLine("state-archive-read-config:")
            appendLine("  - ingestion-url: ${yamlQuote(archiveUrl)}")
            appendLine("    concurrency: $archiveConcurrency")
        }
    }

    private fun yamlQuote(raw: String): String
    {
        val escaped = raw.replace("\\", "\\\\").replace("\"", "\\\"")
        return "\"$escaped\""
    }
}
