package main

import (
	"strings"
	"testing"
)

func TestRenderBitcoinConfBodyWithCache_ProdRPCKeys(t *testing.T) {
	cfg := Config{
		Network:      "bitcoin",
		Env:          "mainnet",
		DataDir:      "/data/bitcoin/mainnet",
		UpstreamPort: 8332,
		P2PPort:      8333,
	}

	body := renderBitcoinConfBodyWithCache(cfg, 4096)

	want := []string{
		"server=1",
		"txindex=1",
		"prune=0",
		"disablewallet=1",
		"daemon=0",
		"datadir=/data/bitcoin/mainnet",
		"dbcache=4096",
		"rpcthreads=64",
		"rpcworkqueue=1024",
		"maxconnections=125",
		"rest=1",
		"rpcbind=127.0.0.1",
		"rpcallowip=127.0.0.1",
		"port=8333",
		"rpcport=8332",
	}
	for _, k := range want {
		if !strings.Contains(body, k+"\n") && !strings.HasSuffix(body, k) {
			t.Fatalf("missing %q in:\n%s", k, body)
		}
	}

	if strings.Contains(body, "dbcache=2048") {
		t.Fatalf("stale dbcache=2048 still present")
	}
}

func TestBitcoinDBCacheMB_Bounds(t *testing.T) {
	// When /proc/meminfo unavailable (macOS CI), default is 4096.
	c := bitcoinDBCacheMB()
	if c < 2048 || c > 8192 {
		t.Fatalf("dbcache out of bounds: %d", c)
	}
}

func TestIsAgentGeneratedBitcoinConf(t *testing.T) {
	if !isAgentGeneratedBitcoinConf([]byte("# Generated by rpcnode system-agent — do not edit by hand\nserver=1\n")) {
		t.Fatal("expected agent-generated")
	}
	if isAgentGeneratedBitcoinConf([]byte("server=1\ntxindex=1\n")) {
		t.Fatal("hand-edited must not be treated as agent-generated")
	}
}
