#!/usr/bin/env bash
# Interactive / non-interactive installer for EXISTING (or fresh) TRON nodes.
# Never destroys chain DB by default.

# Interactive port conflict resolver.
# Sets globals: SETUP_RESOLVED_GW_PORT, SETUP_RESOLVED_PANEL_PORT, SETUP_RESOLVED_HTTP_PORT
_setup_resolve_ports() {
  local gw_port="$1" http_port="$2" panel_port="${3:-}" alt yn new_port
  SETUP_RESOLVED_GW_PORT="$gw_port"
  SETUP_RESOLVED_HTTP_PORT="$http_port"
  SETUP_RESOLVED_PANEL_PORT="${panel_port:-${TRON_PANEL_PORT:-}}"

  if port_is_busy "$SETUP_RESOLVED_GW_PORT"; then
    alt="$(suggest_free_port "$SETUP_RESOLVED_GW_PORT")"
    warn "RPC public port ${SETUP_RESOLVED_GW_PORT} is BUSY"
    info "suggestion: use ${alt} (or free the port: ss -lntp | grep :${SETUP_RESOLVED_GW_PORT})"
    if [[ "${SETUP_NONINTERACTIVE:-0}" == "1" ]]; then
      if [[ "${SETUP_STRICT_PREFLIGHT:-0}" == "1" ]]; then
        die "port ${SETUP_RESOLVED_GW_PORT} busy — pass --gateway-port ${alt} or free it"
      fi
      warn "non-interactive: switching RPC port ${SETUP_RESOLVED_GW_PORT} → ${alt}"
      SETUP_RESOLVED_GW_PORT="$alt"
    else
      yn="y"
      _setup_yn "Use free port ${alt} instead of ${SETUP_RESOLVED_GW_PORT}?" "y" yn
      if [[ "$yn" == "y" ]]; then
        SETUP_RESOLVED_GW_PORT="$alt"
      else
        _setup_ask "Enter different RPC public port" "$alt" new_port
        SETUP_RESOLVED_GW_PORT="$new_port"
        if port_is_busy "$SETUP_RESOLVED_GW_PORT"; then
          die "port ${SETUP_RESOLVED_GW_PORT} still busy — aborting"
        fi
      fi
    fi
  else
    ok "RPC public port ${SETUP_RESOLVED_GW_PORT} is free"
  fi

  if [[ -n "${SETUP_RESOLVED_PANEL_PORT}" ]]; then
    if port_is_busy "$SETUP_RESOLVED_PANEL_PORT"; then
      alt="$(suggest_free_port "$SETUP_RESOLVED_PANEL_PORT")"
      warn "Panel port ${SETUP_RESOLVED_PANEL_PORT} is BUSY"
      if [[ "${SETUP_NONINTERACTIVE:-0}" == "1" ]]; then
        warn "non-interactive: switching panel port ${SETUP_RESOLVED_PANEL_PORT} → ${alt}"
        SETUP_RESOLVED_PANEL_PORT="$alt"
      else
        yn="y"
        _setup_yn "Use free panel port ${alt} instead of ${SETUP_RESOLVED_PANEL_PORT}?" "y" yn
        if [[ "$yn" == "y" ]]; then
          SETUP_RESOLVED_PANEL_PORT="$alt"
        else
          _setup_ask "Enter different panel port" "$alt" new_port
          SETUP_RESOLVED_PANEL_PORT="$new_port"
        fi
      fi
    else
      ok "Panel port ${SETUP_RESOLVED_PANEL_PORT} is free"
    fi
  fi

  if port_is_busy "$SETUP_RESOLVED_HTTP_PORT"; then
    alt="$(suggest_free_port "$SETUP_RESOLVED_HTTP_PORT")"
    warn "java-tron HTTP port ${SETUP_RESOLVED_HTTP_PORT} is BUSY"
    info "suggestion: use ${alt} (or point at the existing node with --node-http-port)"
    if [[ "${SETUP_NONINTERACTIVE:-0}" == "1" ]]; then
      if [[ "${SETUP_STRICT_PREFLIGHT:-0}" == "1" ]]; then
        die "port ${SETUP_RESOLVED_HTTP_PORT} busy — pass --node-http-port ${alt}"
      fi
      warn "non-interactive: keeping node HTTP ${SETUP_RESOLVED_HTTP_PORT} (likely existing java-tron)"
    else
      yn="y"
      _setup_yn "Node port ${SETUP_RESOLVED_HTTP_PORT} busy (existing java-tron?). Keep it?" "y" yn
      if [[ "$yn" != "y" ]]; then
        _setup_ask "Enter java-tron HTTP port" "$alt" new_port
        SETUP_RESOLVED_HTTP_PORT="$new_port"
      fi
    fi
  else
    ok "java-tron HTTP port ${SETUP_RESOLVED_HTTP_PORT} is free"
  fi
}

# Prompt helper: SETUP_YES / flags short-circuit.
_setup_ask() {
  local prompt="$1" default="$2" var="$3" reply
  if [[ "${SETUP_NONINTERACTIVE:-0}" == "1" ]]; then
    printf -v "$var" '%s' "$default"
    return 0
  fi
  if [[ ! -t 0 ]]; then
    printf -v "$var" '%s' "$default"
    return 0
  fi
  read -r -p "$prompt [$default]: " reply || true
  if [[ -z "$reply" ]]; then
    printf -v "$var" '%s' "$default"
  else
    printf -v "$var" '%s' "$reply"
  fi
}

_setup_yn() {
  local prompt="$1" default="$2" var="$3" reply
  if [[ "${SETUP_NONINTERACTIVE:-0}" == "1" ]]; then
    printf -v "$var" '%s' "$default"
    return 0
  fi
  if [[ ! -t 0 ]]; then
    printf -v "$var" '%s' "$default"
    return 0
  fi
  read -r -p "$prompt [y/N]: " reply || true
  case "${reply:-$default}" in
    y|Y|yes|YES) printf -v "$var" '%s' "y" ;;
    *) printf -v "$var" '%s' "n" ;;
  esac
}

write_toolkit_env_from_setup() {
  local dest="${TRON_ETC}/toolkit.env"
  mkdir -p "$TRON_ETC"
  cat >"$dest" <<EOF
# Generated by rpcnodectl setup ($(ts))
# Ports: RPC per env 8090/8091/8092; panel default 8093 (bumps only if busy)
TRON_ENV=${TRON_ENV}
TRON_TAG=${TRON_TAG}

TRON_OPT=${TRON_OPT}
TRON_ETC=${TRON_ETC}
TRON_DATA=${TRON_DATA}
TRON_OUTPUT=${TRON_OUTPUT}

TRON_NODE_HTTP_HOST=${TRON_NODE_HTTP_HOST}
TRON_NODE_HTTP_PORT=${TRON_NODE_HTTP_PORT}
TRON_GATEWAY_LISTEN=${TRON_GATEWAY_LISTEN}
TRON_PUBLIC_PORT=${TRON_PUBLIC_PORT:-$TRON_GATEWAY_PORT}
TRON_GATEWAY_PORT=${TRON_PUBLIC_PORT}
TRON_PANEL_PORT=${TRON_PANEL_PORT}
TRON_P2P_PORT=${TRON_P2P_PORT}
TRON_SYSTEM_AGENT_PORT=${TRON_SYSTEM_AGENT_PORT:-}
TRON_PUBLIC_BASE=${TRON_PUBLIC_BASE}
TRON_PANEL_BASE=${TRON_PANEL_BASE:-}
PUBLIC_BASE=${TRON_PUBLIC_BASE}

TRON_SNAPSHOT_URL=${TRON_SNAPSHOT_URL}

TRON_JAVA_XMX=${TRON_JAVA_XMX}
TRON_JAVA_XMS=${TRON_JAVA_XMS}

TRON_MAX_HTTP_CONNECT=${TRON_MAX_HTTP_CONNECT:-2000}
TRON_GLOBAL_QPS=${TRON_GLOBAL_QPS:-200000}
TRON_GLOBAL_IP_QPS=${TRON_GLOBAL_IP_QPS:-200000}

TRON_UPDATER_HOUR_UTC=${TRON_UPDATER_HOUR_UTC:-3}
TRON_UPDATER_AUTO_APPLY=${TRON_UPDATER_AUTO_APPLY:-1}
TRON_UPDATER_WITH_SNAPSHOT=${TRON_UPDATER_WITH_SNAPSHOT:-0}

# Docker-first: Go api-agent (RPC+panel) + system-agent. nginx = optional profile edge.
TRON_DOCKER_FIRST=1
TRON_AGENT_STATE=/var/lib/rpcnode/tron-${TRON_ENV}/agent-state.json
TRON_INSTANCE_FILE=/var/lib/rpcnode/tron-${TRON_ENV}/INSTANCE.json
TRON_REGISTRY_FILE=/etc/rpcnode/instances.d/tron-${TRON_ENV}.json
TRON_PANEL_HTPASSWD=/etc/rpcnode/panel.htpasswd
TRON_PANEL_USER=${TRON_PANEL_USER:-admin}

# Agent key for /api/v1 and future central registration (also as TRON_API_TOKEN).
AGENT_API_TOKEN=${AGENT_API_TOKEN:-}
TRON_API_TOKEN=${TRON_API_TOKEN:-${AGENT_API_TOKEN:-}}
AGENT_DOWNLOAD_URL=${AGENT_DOWNLOAD_URL:-https://toolkit.rpcnode.dev/install/agent.sh}
EOF
  chown "root:${TRON_GROUP}" "$dest" 2>/dev/null || true
  chmod 640 "$dest"
  ok "wrote $dest"
}

# Generate AGENT_API_TOKEN once if missing (machine agents / central control plane).
ensure_agent_api_token() {
  if [[ -n "${AGENT_API_TOKEN:-}" ]]; then
    TRON_API_TOKEN="${TRON_API_TOKEN:-$AGENT_API_TOKEN}"
    export AGENT_API_TOKEN TRON_API_TOKEN
    return 0
  fi
  if [[ -n "${TRON_API_TOKEN:-}" ]]; then
    AGENT_API_TOKEN="$TRON_API_TOKEN"
    export AGENT_API_TOKEN TRON_API_TOKEN
    return 0
  fi
  AGENT_API_TOKEN="$(openssl rand -hex 32 2>/dev/null || head -c 32 /dev/urandom | xxd -p -c 64)"
  TRON_API_TOKEN="$AGENT_API_TOKEN"
  export AGENT_API_TOKEN TRON_API_TOKEN
  ok "generated AGENT_API_TOKEN (save for central registration)"
  info "agent key: ${AGENT_API_TOKEN}"
}

# Soft-link toolkit into a stable root if we're running from a temp path.
ensure_toolkit_install_root() {
  local target="${SETUP_TOOLKIT_ROOT:-/opt/rpcnode/deploy/nodes/tron/toolkit}"
  if [[ "$TOOLKIT_DIR" == "$target" ]]; then
    return 0
  fi
  if [[ "${SETUP_COPY_TOOLKIT:-1}" != "1" ]]; then
    info "using toolkit in-place: $TOOLKIT_DIR"
    return 0
  fi
  require_root
  mkdir -p "$(dirname "$target")"
  if [[ -d "$target/.git" ]] || [[ -f "$target/rpcnodectl" || -f "$target/tronctl" ]]; then
    info "sync toolkit → $target"
    rsync -a --delete \
      --exclude '.git' \
      --exclude 'bin/' \
      "$TOOLKIT_DIR"/ "$target"/
  else
    info "install toolkit → $target"
    mkdir -p "$target"
    rsync -a --exclude '.git' "$TOOLKIT_DIR"/ "$target"/
  fi
  TOOLKIT_DIR="$target"
  chmod +x "$TOOLKIT_DIR/rpcnodectl" "$TOOLKIT_DIR/tronctl" 2>/dev/null || true
  ln -sfn "$TOOLKIT_DIR/rpcnodectl" /usr/local/bin/rpcnodectl
  ln -sfn "$TOOLKIT_DIR/tronctl" /usr/local/bin/tronctl
  ok "rpcnodectl → /usr/local/bin/rpcnodectl ($TOOLKIT_DIR)"
}

cmd_setup() {
  require_root

  local write_registry_only=0
  local gateway_only=0
  local install_node=0
  local assume_defaults=0
  local mode="existing"

  SETUP_NONINTERACTIVE=0
  SETUP_COPY_TOOLKIT=1
  SETUP_STRICT_PREFLIGHT=0
  SETUP_SKIP_PREFLIGHT=0

  while [[ $# -gt 0 ]]; do
    case "$1" in
      --non-interactive|--yes|-y)
        SETUP_NONINTERACTIVE=1
        assume_defaults=1
        shift
        ;;
      --wizard)
        SETUP_NONINTERACTIVE=0
        shift
        ;;
      --strict-preflight)
        SETUP_STRICT_PREFLIGHT=1
        shift
        ;;
      --skip-preflight)
        SETUP_SKIP_PREFLIGHT=1
        shift
        ;;
      --accept-unsuitable|--force)
        # synonym: continue even if FAIL (default in non-interactive already)
        SETUP_STRICT_PREFLIGHT=0
        shift
        ;;
      --env)
        TRON_ENV="$2"
        export TRON_ENV
        shift 2
        ;;
      --gateway-only)
        gateway_only=1
        mode="gateway-only"
        shift
        ;;
      --with-node)
        install_node=1
        mode="fresh"
        shift
        ;;
      --write-registry)
        write_registry_only=1
        shift
        ;;
      --no-copy)
        SETUP_COPY_TOOLKIT=0
        shift
        ;;
      --toolkit-root)
        SETUP_TOOLKIT_ROOT="$2"
        shift 2
        ;;
      --public-base)
        TRON_PUBLIC_BASE="$2"
        _SETUP_CLI_PUBLIC_BASE="$2"
        shift 2
        ;;
      --gateway-listen)
        TRON_GATEWAY_LISTEN="$2"
        shift 2
        ;;
      --gateway-port|--public-port)
        TRON_GATEWAY_PORT="$2"
        TRON_PUBLIC_PORT="$2"
        _SETUP_CLI_GATEWAY_PORT="$2"
        shift 2
        ;;
      --panel-port)
        TRON_PANEL_PORT="$2"
        _SETUP_CLI_PANEL_PORT="$2"
        shift 2
        ;;
      --node-http-port)
        TRON_NODE_HTTP_PORT="$2"
        _SETUP_CLI_NODE_HTTP_PORT="$2"
        shift 2
        ;;
      --p2p-port)
        TRON_P2P_PORT="$2"
        _SETUP_CLI_P2P_PORT="$2"
        shift 2
        ;;
      --data-dir)
        TRON_DATA="$2"
        TRON_OUTPUT="${TRON_DATA}/output-directory"
        shift 2
        ;;
      --panel-user)
        TRON_PANEL_USER="$2"
        shift 2
        ;;
      --panel-password)
        TRON_PANEL_PASSWORD="$2"
        shift 2
        ;;
      --help|-h)
        cat <<EOF
rpcnodectl setup — install toolkit on an EXISTING (or fresh) java-tron node

Usage:
  sudo rpcnodectl setup [--wizard]
  sudo rpcnodectl setup --non-interactive [flags]
  sudo rpcnodectl setup --write-registry
  sudo rpcnodectl install --wizard   # alias

Flags:
  --env mainnet|nile|shasta
  --non-interactive / --yes      no prompts (use flags + detection defaults)
  --gateway-only                 only gateway + toolkit units (node already managed)
  --with-node                    also install/enable java-tron systemd unit
  --no-copy                      do not rsync toolkit to /opt/rpcnode/...
  --toolkit-root PATH
  --public-base URL              e.g. http://IP:8090 (port must match gateway)
  --gateway-listen ADDR          default 0.0.0.0 (status UI reachable)
  --gateway-port / --public-port PORT
                                 RPC public port (mainnet 8090, nile 8091, shasta 8092)
  --panel-port PORT              ops panel port (default 8093 all envs; bumps if busy)
  --node-http-port PORT          java-tron HTTP (defaults: 18090 / 18091 / 18092)
  --p2p-port PORT                default 18888 / 18889 / 18890
  --data-dir PATH                existing chain data parent (NOT wiped)
  --panel-user NAME              ops console basic-auth user (default admin)
  --panel-password SECRET        ops console basic-auth password (set at install)
  --strict-preflight             abort setup if preflight has FAIL
  --skip-preflight               do not run host checks
  --accept-unsuitable / --force  continue despite FAIL (default non-interactive)
  --write-registry               only refresh instance registry JSON

Preflight (non-blocking): CPU/RAM/disk/OS/Docker/ports — shows OK/WARN/FAIL,
what exactly doesn't fit, then asks to continue (wizard) or continues with
warnings (non-interactive). Use --strict-preflight to fail the install.

Go dual ports: RPC catch-all (no auth) + panel /status+/api (htpasswd).
Change later: rpcnodectl panel-auth set --user U --password P

Safety: never deletes output-directory / chain DB unless you later run
        snapshot replace / upgrade --with-snapshot explicitly.
EOF
        return 0
        ;;
      *)
        warn "unknown setup flag: $1"
        shift
        ;;
    esac
  done

  # Reload paths for chosen env
  # shellcheck disable=SC1091
  source "$TOOLKIT_DIR/lib/paths.sh"

  if [[ "$write_registry_only" -eq 1 ]]; then
    write_instance_registry "${mode}"
    cmd_where || true
    return 0
  fi

  info "TRON toolkit setup (env=${TRON_ENV})"
  detect_existing_node
  print_detection_report
  echo

  local ans_env ans_opt ans_etc ans_data ans_http ans_gw_listen ans_gw_port ans_public ans_mode
  local def_env="${TRON_ENV}"
  local def_opt="${TRON_OPT}"
  local def_etc="${TRON_ETC}"
  local def_data="${DETECT_DATA_DIR:-$TRON_DATA}"
  local def_gw_listen="${TRON_GATEWAY_LISTEN:-0.0.0.0}"
  # Prefer public bind for status UI on existing nodes
  [[ "$def_gw_listen" == "127.0.0.1" && "$assume_defaults" -eq 0 ]] && def_gw_listen="0.0.0.0"

  if [[ "$DETECT_NODE_RUNNING" -eq 1 || "$DETECT_HAS_DATA" -eq 1 ]]; then
    mode="existing"
    gateway_only=1
  fi
  if [[ "$install_node" -eq 1 ]]; then
    mode="fresh"
    gateway_only=0
  fi

  echo
  print_port_scheme
  echo

  _setup_ask "NETWORK_ENV (mainnet/nile/shasta)" "$def_env" ans_env
  TRON_ENV="$ans_env"
  export TRON_ENV
  # Re-load paths for chosen env; re-apply per-env port defaults unless CLI forced them
  unset TRON_GATEWAY_PORT TRON_PUBLIC_PORT TRON_PANEL_PORT TRON_NODE_HTTP_PORT TRON_P2P_PORT \
        TRON_SYSTEM_AGENT_PORT 2>/dev/null || true
  # shellcheck disable=SC1091
  source "$TOOLKIT_DIR/lib/paths.sh"
  apply_env_port_defaults
  [[ -n "${_SETUP_CLI_GATEWAY_PORT:-}" ]] && TRON_GATEWAY_PORT="$_SETUP_CLI_GATEWAY_PORT" && TRON_PUBLIC_PORT="$_SETUP_CLI_GATEWAY_PORT"
  [[ -n "${_SETUP_CLI_PANEL_PORT:-}" ]] && TRON_PANEL_PORT="$_SETUP_CLI_PANEL_PORT"
  [[ -n "${_SETUP_CLI_NODE_HTTP_PORT:-}" ]] && TRON_NODE_HTTP_PORT="$_SETUP_CLI_NODE_HTTP_PORT"
  [[ -n "${_SETUP_CLI_P2P_PORT:-}" ]] && TRON_P2P_PORT="$_SETUP_CLI_P2P_PORT"
  [[ -n "${_SETUP_CLI_PUBLIC_BASE:-}" ]] && TRON_PUBLIC_BASE="$_SETUP_CLI_PUBLIC_BASE"

  def_opt="/opt/tron/${TRON_ENV}"
  def_etc="/etc/tron/${TRON_ENV}"
  def_data="${DETECT_DATA_DIR:-/data/tron/${TRON_ENV}}"
  local def_http="${DETECT_HTTP_PORT:-$TRON_NODE_HTTP_PORT}"
  # Prefer detected HTTP only when it matches this env's default or CLI override
  if [[ -n "${DETECT_HTTP_PORT:-}" && -z "${_SETUP_CLI_NODE_HTTP_PORT:-}" ]]; then
    if [[ "$DETECT_HTTP_PORT" == "$TRON_NODE_HTTP_PORT" ]] || [[ "$DETECT_NODE_RUNNING" -eq 1 ]]; then
      def_http="$DETECT_HTTP_PORT"
    fi
  fi
  local def_gw_port="${TRON_PUBLIC_PORT:-$TRON_GATEWAY_PORT}"
  local def_panel_port="${TRON_PANEL_PORT:-8093}"
  local def_public="${TRON_PUBLIC_BASE:-}"
  local ans_panel_port
  TRON_GATEWAY_PORT="$def_gw_port"
  TRON_PUBLIC_PORT="$def_gw_port"
  if [[ -z "$def_public" ]]; then
    def_public="$(detect_public_base)"
  else
    def_public="$(rebuild_public_base_port "$def_public" "$def_gw_port")"
  fi

  _setup_ask "OPT dir (jar/bin)" "$def_opt" ans_opt
  _setup_ask "ETC dir (config/env)" "$def_etc" ans_etc
  _setup_ask "DATA dir (parent of output-directory) — NOT wiped" "$def_data" ans_data
  _setup_ask "java-tron HTTP port (internal)" "$def_http" ans_http
  _setup_ask "listen address (0.0.0.0 for public RPC+panel)" "$def_gw_listen" ans_gw_listen
  _setup_ask "RPC public port (TRON_PUBLIC_PORT — FullNode proxy)" "$def_gw_port" ans_gw_port
  _setup_ask "Panel port (TRON_PANEL_PORT — ops UI + /api)" "$def_panel_port" ans_panel_port

  # Port preflight early — allow changing busy ports before writing env
  _setup_resolve_ports "$ans_gw_port" "$ans_http" "$ans_panel_port"
  ans_gw_port="$SETUP_RESOLVED_GW_PORT"
  ans_http="$SETUP_RESOLVED_HTTP_PORT"
  ans_panel_port="${SETUP_RESOLVED_PANEL_PORT:-$ans_panel_port}"

  TRON_GATEWAY_PORT="$ans_gw_port"
  TRON_PUBLIC_PORT="$ans_gw_port"
  TRON_PANEL_PORT="$ans_panel_port"
  TRON_NODE_HTTP_PORT="$ans_http"
  def_public="$(rebuild_public_base_port "${def_public}" "$ans_gw_port")"
  [[ -z "$def_public" ]] && def_public="$(detect_public_base)"
  _setup_ask "RPC public base URL (TRON_PUBLIC_BASE — must include :${ans_gw_port})" "$def_public" ans_public
  TRON_PANEL_BASE="$(rebuild_public_base_port "$ans_public" "$ans_panel_port")"

  echo
  info "Ops panel basic auth (htpasswd on panel port :${ans_panel_port}) — credentials are set at install time"
  info "RPC port :${ans_gw_port} stays public catch-all (no panel login). Change password later: rpcnodectl panel-auth set"
  prompt_panel_credentials

  if [[ "$gateway_only" -eq 1 ]]; then
    ans_mode="gateway-only"
  else
    local yn="n"
    if [[ "$DETECT_NODE_RUNNING" -eq 1 ]]; then
      info "java-tron already running — default: gateway+toolkit only (do not touch node unit)"
      _setup_yn "Also (re)write java-tron systemd unit?" "n" yn
    else
      _setup_yn "Install/enable java-tron systemd unit?" "y" yn
    fi
    if [[ "$yn" == "y" ]]; then
      ans_mode="fresh"
      install_node=1
      gateway_only=0
    else
      ans_mode="gateway-only"
      gateway_only=1
      install_node=0
    fi
  fi

  TRON_OPT="$ans_opt"
  TRON_ETC="$ans_etc"
  TRON_DATA="$ans_data"
  TRON_OUTPUT="${TRON_OUTPUT:-${TRON_DATA}/output-directory}"
  # If detected output differs and lives under chosen data — keep it
  if [[ -n "$DETECT_OUTPUT" && "$DETECT_OUTPUT" == "$TRON_DATA"* ]]; then
    TRON_OUTPUT="$DETECT_OUTPUT"
  elif [[ -d "${TRON_DATA}/output-directory" ]]; then
    TRON_OUTPUT="${TRON_DATA}/output-directory"
  fi
  TRON_JAR="${TRON_OPT}/FullNode.jar"
  if [[ -n "$DETECT_JAR" && -f "$DETECT_JAR" && "$DETECT_JAR" != "$TRON_JAR" ]]; then
    info "existing jar at $DETECT_JAR (keeping path if already under OPT, else leave in place)"
    if [[ "$DETECT_JAR" == "$TRON_OPT"* ]]; then
      TRON_JAR="$DETECT_JAR"
    fi
  fi
  TRON_CONFIG="${TRON_CONFIG:-${TRON_ETC}/main_net_config.conf}"
  if [[ -n "$DETECT_CONFIG" && -f "$DETECT_CONFIG" ]]; then
    # Prefer existing config path if under ETC; else copy later without overwrite of data
    if [[ "$DETECT_CONFIG" == "$TRON_ETC"* ]]; then
      TRON_CONFIG="$DETECT_CONFIG"
    fi
  fi
  TRON_NODE_HTTP_PORT="$ans_http"
  TRON_GATEWAY_LISTEN="$ans_gw_listen"
  TRON_GATEWAY_PORT="$ans_gw_port"
  TRON_PUBLIC_PORT="$ans_gw_port"
  TRON_PANEL_PORT="$ans_panel_port"
  TRON_PUBLIC_BASE="$ans_public"
  PUBLIC_BASE="$ans_public"
  apply_env_port_defaults
  # Re-assert chosen ports (apply_env_port_defaults won't override non-empty)
  TRON_GATEWAY_PORT="$ans_gw_port"
  TRON_PUBLIC_PORT="$ans_gw_port"
  TRON_PANEL_PORT="$ans_panel_port"
  TRON_NODE_HTTP_PORT="$ans_http"
  if [[ -n "${DETECT_P2P_PORT:-}" && -z "${_SETUP_CLI_P2P_PORT:-}" && "$DETECT_NODE_RUNNING" -eq 1 ]]; then
    TRON_P2P_PORT="$DETECT_P2P_PORT"
  fi
  TRON_GATEWAY_BIN="${TRON_OPT}/bin/tron-gateway"
  mode="$ans_mode"

  echo
  info "plan:"
  echo "  mode=$mode"
  echo "  env=$TRON_ENV"
  echo "  OPT=$TRON_OPT ETC=$TRON_ETC DATA=$TRON_DATA"
  echo "  OUTPUT=$TRON_OUTPUT  (will NOT be deleted)"
  echo "  node_http=${TRON_NODE_HTTP_HOST}:${TRON_NODE_HTTP_PORT}"
  echo "  RPC=${TRON_GATEWAY_LISTEN}:${TRON_PUBLIC_PORT}  panel=:${TRON_PANEL_PORT}"
  echo "  public_rpc=$TRON_PUBLIC_BASE"
  echo "  panel_base=${TRON_PANEL_BASE:-$(rebuild_public_base_port "$TRON_PUBLIC_BASE" "$TRON_PANEL_PORT")}"
  echo "  panel_user=${PANEL_USER:-admin} (htpasswd set now at install; password not shown)"
  echo "  change later: rpcnodectl panel-auth set --user … --password …"
  echo

  if [[ "$SETUP_SKIP_PREFLIGHT" != "1" ]]; then
    local need_java=0
    [[ "$install_node" -eq 1 ]] && need_java=1
    run_preflight "$TRON_DATA" "$TRON_GATEWAY_PORT" "$need_java" "$TRON_NODE_HTTP_PORT"
    preflight_confirm_continue || die "aborted after preflight"
  else
    warn "preflight skipped (--skip-preflight)"
  fi

  if [[ "$SETUP_NONINTERACTIVE" != "1" ]]; then
    local go
    _setup_yn "Proceed with install?" "y" go
    [[ "$go" == "y" ]] || die "aborted"
  fi

  # Refuse accidental wipe markers
  if [[ -d "$TRON_OUTPUT" ]]; then
    ok "preserving existing chain data: $TRON_OUTPUT"
    DETECT_HAS_DATA=1
  fi

  ensure_toolkit_install_root
  # shellcheck disable=SC1091
  source "$TOOLKIT_DIR/lib/paths.sh"
  # Re-apply choices after reload (paths.sh may overwrite from old env file)
  TRON_OPT="$ans_opt"
  TRON_ETC="$ans_etc"
  TRON_DATA="$ans_data"
  TRON_OUTPUT="${TRON_OUTPUT:-${TRON_DATA}/output-directory}"
  TRON_NODE_HTTP_PORT="$ans_http"
  TRON_GATEWAY_LISTEN="$ans_gw_listen"
  TRON_GATEWAY_PORT="$ans_gw_port"
  TRON_PUBLIC_PORT="$ans_gw_port"
  TRON_PANEL_PORT="$ans_panel_port"
  TRON_PUBLIC_BASE="$ans_public"
  PUBLIC_BASE="$ans_public"
  TRON_PANEL_BASE="$(rebuild_public_base_port "$ans_public" "$ans_panel_port")"
  TRON_GATEWAY_BIN="${TRON_OPT}/bin/tron-gateway"
  TRON_JAR="${TRON_JAR:-${TRON_OPT}/FullNode.jar}"
  TRON_CONFIG="${TRON_CONFIG:-${TRON_ETC}/main_net_config.conf}"
  TRON_VERSION_FILE="${TRON_OPT}/VERSION"
  TRON_SERVICE="tron-${TRON_ENV}"
  TRON_SNAPSHOT_SERVICE="tron-${TRON_ENV}-snapshot"
  TRON_GATEWAY_SERVICE="tron-${TRON_ENV}-gateway"
  TRON_UPDATER_SERVICE="tron-${TRON_ENV}-updater"
  TRON_UPDATER_TIMER="tron-${TRON_ENV}-updater.timer"
  TRON_MAINTENANCE_FILE="/run/tron-${TRON_ENV}/maintenance.json"
  TRON_SNAPSHOT_MARKER="${TRON_DATA}/.snapshot-ready"
  TRON_SNAPSHOT_STATE="${TRON_DATA}/.snapshot-state.json"
  TRON_UPDATER_STATE="${TRON_DATA}/.updater-state.json"
  apply_env_port_defaults
  TRON_GATEWAY_PORT="$ans_gw_port"
  TRON_PUBLIC_PORT="$ans_gw_port"
  TRON_PANEL_PORT="$ans_panel_port"
  TRON_NODE_HTTP_PORT="$ans_http"

  export DEBIAN_FRONTEND=noninteractive
  apt-get update -qq 2>/dev/null || true
  apt-get install -y -qq curl jq tar wget ca-certificates rsync apache2-utils openssl 2>/dev/null || true
  # Docker is optional here (panel runs elsewhere). Host agents use systemd binaries.

  ensure_dirs
  TRON_PANEL_USER="${PANEL_USER:-admin}"
  ensure_agent_api_token
  : "${AGENT_DOWNLOAD_URL:=https://toolkit.rpcnode.dev/install/agent.sh}"
  export AGENT_DOWNLOAD_URL
  write_toolkit_env_from_setup
  write_panel_htpasswd "${PANEL_USER:-admin}" "${PANEL_PASSWORD}"

  # Config: copy detected into ETC if missing; never overwrite good existing without backup
  if [[ ! -f "$TRON_CONFIG" ]]; then
    if [[ -n "$DETECT_CONFIG" && -f "$DETECT_CONFIG" ]]; then
      mkdir -p "$(dirname "$TRON_CONFIG")"
      cp -a "$DETECT_CONFIG" "$TRON_CONFIG"
      ok "copied config → $TRON_CONFIG"
    elif [[ "$install_node" -eq 1 ]]; then
      info "download config ${TRON_TAG}"
      curl -fL -o "$TRON_CONFIG" "$TRON_CONFIG_URL"
      patch_config_ports "$TRON_CONFIG"
    else
      warn "no config at $TRON_CONFIG (gateway-only ok if node uses its own path)"
    fi
  else
    info "keep existing config $TRON_CONFIG"
    patch_config_prod_limits "$TRON_CONFIG" || true
  fi

  # Jar for fresh node install only
  if [[ "$install_node" -eq 1 && ! -f "$TRON_JAR" ]]; then
    if [[ -n "$DETECT_JAR" && -f "$DETECT_JAR" ]]; then
      mkdir -p "$(dirname "$TRON_JAR")"
      cp -a "$DETECT_JAR" "$TRON_JAR"
      ok "copied jar → $TRON_JAR"
    else
      info "download jar ${TRON_TAG}"
      curl -fL --retry 5 -o "$TRON_JAR" "$TRON_JAR_URL"
    fi
    chown "${TRON_USER}:${TRON_GROUP}" "$TRON_JAR" 2>/dev/null || true
  fi

  if [[ ! -f "$TRON_VERSION_FILE" ]]; then
    cat >"$TRON_VERSION_FILE" <<EOF
tag=${TRON_TAG}
jar=FullNode.jar
snapshot_url=${TRON_SNAPSHOT_URL}
installed_at=$(ts)
layout=${TRON_ENV}-isolated
setup_mode=${mode}
node_http=${TRON_NODE_HTTP_HOST}:${TRON_NODE_HTTP_PORT}
gateway=${TRON_GATEWAY_LISTEN}:${TRON_GATEWAY_PORT}
EOF
  fi

  # If data looks ready, mark snapshot so UI is not stuck in wizard forever
  if [[ -d "$TRON_OUTPUT" ]] && [[ ! -f "$TRON_SNAPSHOT_MARKER" ]]; then
    # Heuristic: database dir present
    if [[ -d "$TRON_OUTPUT/database" ]] || [[ -d "$TRON_OUTPUT/Database" ]] || [[ "$(ls -A "$TRON_OUTPUT" 2>/dev/null | head -1)" ]]; then
      date -u +"%Y-%m-%dT%H:%M:%SZ" >"$TRON_SNAPSHOT_MARKER"
      ok "wrote snapshot marker (existing data): $TRON_SNAPSHOT_MARKER"
    fi
  fi

  if [[ "$install_node" -eq 1 ]]; then
    write_node_unit
    systemctl enable "${TRON_SERVICE}.service"
    info "node unit installed (not restarted unless inactive)"
    if ! systemctl is-active --quiet "${TRON_SERVICE}.service" 2>/dev/null \
       && [[ "$DETECT_NODE_RUNNING" -eq 0 ]]; then
      warn "node not running — start when ready: systemctl start ${TRON_SERVICE}"
    fi
  else
    info "skipping node unit (gateway-only / existing node)"
  fi

  # Snapshot/updater units remain optional host helpers (node may be on host).
  write_snapshot_unit 2>/dev/null || true
  write_updater_units 2>/dev/null || true
  systemctl daemon-reload 2>/dev/null || true
  systemctl enable "${TRON_UPDATER_TIMER}" 2>/dev/null || true

  ln -sfn "$TOOLKIT_DIR/rpcnodectl" /usr/local/bin/rpcnodectl
  ln -sfn "$TOOLKIT_DIR/tronctl" /usr/local/bin/tronctl
  ensure_host_runtime_dirs
  write_instance_registry "$mode"

  # Host agents = Go binaries + systemd (not Docker).
  info "installing/updating host agents via ${AGENT_DOWNLOAD_URL:-https://toolkit.rpcnode.dev/install/agent.sh}"
  if curl -fsSL "${AGENT_DOWNLOAD_URL:-https://toolkit.rpcnode.dev/install/agent.sh}" | bash; then
    ok "host agents installed (systemd)"
  else
    warn "agent install failed — run: curl -fsSL https://toolkit.rpcnode.dev/install/agent.sh | sudo bash"
  fi
  cmd_agents status 2>/dev/null || true

  local panel_base="${TRON_PANEL_BASE:-}"
  [[ -z "$panel_base" ]] && panel_base="$(rebuild_public_base_port "$TRON_PUBLIC_BASE" "$TRON_PANEL_PORT")"

  echo
  ok "setup complete (mode=$mode, stack=api-agent+system-agent via systemd)"
  info "agents: rpcnodectl agents up|down|status   (systemd rpcnode-*-agent)"
  info "RPC:    ${TRON_PUBLIC_BASE}/wallet/getnowblock  (catch-all FullNode proxy, no auth)"
  info "panel:  separate control host — docker compose -f docker-compose.panel.yml up -d --build"
  info "auth:   panel login / setup-password — or rpcnodectl panel-auth set --user U --password P"
  info "agent:  see /etc/rpcnode/register.txt for URL + AGENT_API_TOKEN"
  info "where:  rpcnodectl where"
  cmd_where || true
}
